// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {config} from '../models';
import {main} from '../models';

export function AddSearchTerm(arg1:string):Promise<boolean>;

export function Browse(arg1:number,arg2:number,arg3:boolean):Promise<Array<database.Wallpaper>>;

export function BrowseSorted(arg1:number,arg2:number,arg3:boolean,arg4:string):Promise<Array<database.Wallpaper>>;

export function BrowseSortedFiltered(arg1:number,arg2:number,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string):Promise<database.SearchResult>;

export function BrowseTotalCount(arg1:number,arg2:boolean,arg3:string,arg4:string,arg5:string,arg6:string):Promise<number>;

export function CancelDownload(arg1:number):Promise<void>;

export function CleanupCache():Promise<number>;

export function ClearAllStorage():Promise<void>;

export function ClearStorage(arg1:string):Promise<void>;

export function CompleteOnboarding(arg1:string,arg2:Array<string>,arg3:number):Promise<void>;

export function DeleteWallpaper(arg1:number):Promise<void>;

export function DownloadAndSetWallpaper(arg1:number):Promise<void>;

export function DownloadWallpaper(arg1:number):Promise<void>;

export function GetCategoryStats():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<config.Config>;

export function GetDownloadQueue():Promise<Record<string, number>>;

export function GetDownloadedWallpapers(arg1:number,arg2:number,arg3:string):Promise<Array<database.Wallpaper>>;

export function GetProviders():Promise<Array<string>>;

export function GetSearchTerms():Promise<Array<string>>;

export function GetSourceStats():Promise<Array<Record<string, any>>>;

export function GetSources():Promise<Array<database.Source>>;

export function GetStats():Promise<Record<string, any>>;

export function GetStorageInfo():Promise<Array<main.StorageItem>>;

export function GetWallpaper(arg1:number):Promise<database.Wallpaper>;

export function IsFirstRun():Promise<boolean>;

export function IsSourceEnabled(arg1:string):Promise<boolean>;

export function RemoveSearchTerm(arg1:string):Promise<boolean>;

export function ResetDatabase():Promise<void>;

export function ScrapeAll(arg1:number):Promise<Record<string, number>>;

export function Search(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<database.SearchResult>;

export function SelectFolder():Promise<string>;

export function SetConcurrentDownloads(arg1:number):Promise<void>;

export function SetMaxCacheSizeMB(arg1:number):Promise<void>;

export function SetWallpaper(arg1:number):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<void>;

export function ToggleSource(arg1:string):Promise<void>;
