// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSearchTerm(arg1) {
  return window['go']['main']['App']['AddSearchTerm'](arg1);
}

export function AnalysisStats() {
  return window['go']['main']['App']['AnalysisStats']();
}

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function AnalyzeAll() {
  return window['go']['main']['App']['AnalyzeAll']();
}

export function AnalyzeWallpaper(arg1) {
  return window['go']['main']['App']['AnalyzeWallpaper'](arg1);
}

export function Browse(arg1, arg2, arg3) {
  return window['go']['main']['App']['Browse'](arg1, arg2, arg3);
}

export function BrowseSorted(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseSorted'](arg1, arg2, arg3, arg4);
}

export function BrowseSortedFiltered(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['BrowseSortedFiltered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BrowseTotalCount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['BrowseTotalCount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CleanupCache() {
  return window['go']['main']['App']['CleanupCache']();
}

export function ClearAllStorage() {
  return window['go']['main']['App']['ClearAllStorage']();
}

export function ClearStorage(arg1) {
  return window['go']['main']['App']['ClearStorage'](arg1);
}

export function CollectionWallpapers(arg1) {
  return window['go']['main']['App']['CollectionWallpapers'](arg1);
}

export function CompleteOnboarding(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1, arg2, arg3);
}

export function DeleteDuplicates() {
  return window['go']['main']['App']['DeleteDuplicates']();
}

export function DeleteWallpaper(arg1) {
  return window['go']['main']['App']['DeleteWallpaper'](arg1);
}

export function DismissOnboarding() {
  return window['go']['main']['App']['DismissOnboarding']();
}

export function DownloadAndSetWallpaper(arg1) {
  return window['go']['main']['App']['DownloadAndSetWallpaper'](arg1);
}

export function DownloadWallpaper(arg1) {
  return window['go']['main']['App']['DownloadWallpaper'](arg1);
}

export function FindSimilar(arg1, arg2) {
  return window['go']['main']['App']['FindSimilar'](arg1, arg2);
}

export function GetCategoryStats() {
  return window['go']['main']['App']['GetCategoryStats']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadQueue() {
  return window['go']['main']['App']['GetDownloadQueue']();
}

export function GetDownloadedWallpapers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDownloadedWallpapers'](arg1, arg2, arg3);
}

export function GetDuplicates() {
  return window['go']['main']['App']['GetDuplicates']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSearchTerms() {
  return window['go']['main']['App']['GetSearchTerms']();
}

export function GetSourceStats() {
  return window['go']['main']['App']['GetSourceStats']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetWallpaper(arg1) {
  return window['go']['main']['App']['GetWallpaper'](arg1);
}

export function GetWallpaperLabels(arg1) {
  return window['go']['main']['App']['GetWallpaperLabels'](arg1);
}

export function GetWallpapersByIDs(arg1) {
  return window['go']['main']['App']['GetWallpapersByIDs'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsSourceEnabled(arg1) {
  return window['go']['main']['App']['IsSourceEnabled'](arg1);
}

export function PauseAnalysis() {
  return window['go']['main']['App']['PauseAnalysis']();
}

export function ReanalyzeAll() {
  return window['go']['main']['App']['ReanalyzeAll']();
}

export function RemoveSearchTerm(arg1) {
  return window['go']['main']['App']['RemoveSearchTerm'](arg1);
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function ResumeAnalysis() {
  return window['go']['main']['App']['ResumeAnalysis']();
}

export function ScrapeAll(arg1) {
  return window['go']['main']['App']['ScrapeAll'](arg1);
}

export function Search(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchByColor(arg1, arg2) {
  return window['go']['main']['App']['SearchByColor'](arg1, arg2);
}

export function SemanticSearch(arg1, arg2) {
  return window['go']['main']['App']['SemanticSearch'](arg1, arg2);
}

export function SetConcurrentDownloads(arg1) {
  return window['go']['main']['App']['SetConcurrentDownloads'](arg1);
}

export function SetMaxCacheSizeMB(arg1) {
  return window['go']['main']['App']['SetMaxCacheSizeMB'](arg1);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}

export function SetWallpaperLabels(arg1, arg2) {
  return window['go']['main']['App']['SetWallpaperLabels'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleSource(arg1) {
  return window['go']['main']['App']['ToggleSource'](arg1);
}
